version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/empty-repo
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
